#!/usr/bin/python 
pi= 3.1415926535897931159979634685441852
n = int(raw_input('Valor de n: ')) 
suma=0
while n <=0:
  print 'El numero de intervalos debe ser mayor que o'
  n = int(raw_input('Valor de n: '))
for i in range (1,n+1):
    a = float (i-1)/n
    b = float (i)/n
    x_i=(i-0.5)/float (n)  
    fx_i=4/(1+x_i*x_i) 
    print 'Subintervalo' ,[a,b],'x_i=',x_i,'fx_i',fx_i
    suma=suma + fx_i
    pi2= float (suma)/n

print 'El valor aproximado de pi es: ',pi2
print 'El valor de pi con 35 decimales es: %1.35g'%pi
